workspace:
  base: /go
  path: src/github.com/avesanen/dropdead

pipeline:
  build:
    image: golang:1.8.3
    commands:
      - go get .
      - go build
      - go get -t
      - go test -v
  deploy:
    image: appleboy/drone-ssh
    user: ${SSH_USERNAME}
    host: ${SSH_HOST}
    key: ${SSH_KEY}
    secrets: [ ssh_username, ssh_host, ssh_key ]
    port: 22
    script:
      - cd ~/go/src/github.com/avesanen/dropdead
      - git pull
      - docker-compose build
      - docker-compose up -d

