workspace:
  base: /go
  path: src/github.com/avesanen/dropdead

pipeline:
  build:
    image: golang:1.8.3
    commands:
      - go get .
      - go build
      - go get -t
      - go test -v
  ssh:
    image: appleboy/drone-ssh
    host: matrix.glitch.fi
    environment:
      - DRONE_MATRIX_PRIV_KEY=${DRONE_MATRIX_PRIV_KEY}
    username: avesanen
    key: ${DRONE_MATRIX_PRIV_KEY}
    port: 22
    script:
      - cd ~/go/src/github.com/avesanen/dropdead
      - git pull
      - docker-compose build
      - docker-compose up -d
